import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import One from "../components/One";
import PrivacyPolicy from '../components/privacy-policy';
import { useCounter } from "../lib/CounterContext";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { state } = useCounter();


  return <PrivacyPolicy/>


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>{state.count}</h1>

        <hr />
        <One />
      </main>
    </div>
  );
};

export default Home
